### ISSUE TITLE
Add confirmation to clear history

### ISSUE THREAD

**Issue by SargonCZ** [SargonCZ/laser-calculator#6]
# Problem description

There is a menu `Option` with two buttons, `Show history` and `Clear history`. The problem is, that the buttons are close one to another and it's easy to delete the history instead of showing it. This process is irreversible. 

# Possible solution

This can be easily fixed by doing the following:

1.  Ask for confirmation before deleting the history.
2. (Optional) Add a separator between the two buttons.

## Additional details

`tkinter` is used for the GUI, so you will need to use the documentation at [tkdocs.com](https://tkdocs.com). You will be interested in the `askyesno` dialog (see [here](https://tkdocs.com/tutorial/windows.html#dialogs)). The `separator` is described [here](https://tkdocs.com/tutorial/menus.html). You will have to maybe add `from tkinter import messagebox` to the header.

The menu is created in the main class `Calculator` like this 

https://github.com/SargonCZ/laser-calculator/blob/9675425834e7c90ecfbad657703596b9bdb31ffc/laser-calculator.py#L62-L70

Here, you will have to add the separator.

The `Clear history` is defined in this function:

https://github.com/SargonCZ/laser-calculator/blob/9675425834e7c90ecfbad657703596b9bdb31ffc/laser-calculator.py#L132-L139

You have to add the confirmation there.

**Comment by PawelS23** [comment]
I will work on this part.

**Comment by SargonCZ** [comment]
@PawelS23 If you can, do it today. There are a lot of changes, so I would like to make a new release.
