### ISSUE TITLE
Option to open the function definitions from within the program

### ISSUE THREAD

**Issue by SargonCZ** [SargonCZ/laser-calculator#7]
# Motivation

When someone installs the program using the `.msi` installer to the default location, it is hard to locate the `functions.json` and `constants.json` files, as well as the `formulas` folder. However, reaching these is necessary, if you want to extend the functionality of the program.

# Task description

Add a new menu called e.g. `Edit` by similar procedure as the one used here

https://github.com/SargonCZ/laser-calculator/blob/9675425834e7c90ecfbad657703596b9bdb31ffc/laser-calculator.py#L65-L68

This menu will have three commands, for opening the two files in the default editor and the mentioned folder in the file explorer. Relative path to the targeted files/folder can be used, so this will be simple. Since the three indiviual functions should be very short and contain only one command, they can be written as arguments of the `command` keyword with lambda notation.

**Comment by Aadityajoshi151** [comment]
Please have a look at the [PR](https://github.com/SargonCZ/laser-calculator/pull/8) for this.

**Comment by SargonCZ** [comment]
Hi @Aadityajoshi151, thanks. It works well. However, when I look at it, maybe calling it _(Re)define functions_ and _(Re)define contanst_ could be better? 

Could you also update the readme? You don't have to update all the screenshots, but make a mention in the the [appropriate section](https://github.com/SargonCZ/laser-calculator#adding-new-functions) abou thte possibility to open the files form the program itself. 

Afterwards, I will approve the PR.

**Comment by Aadityajoshi151** [comment]
Hi @SargonCZ
I am sorry for asking again but I am afraid I did not understand it.
Are you talking about replacing "Open functions.json" and "Open constants.json" with "(Re)define functions" and "(Re)define constants" respectively?

**Comment by SargonCZ** [comment]
Exactly. Maybe it will be more user friendly? But I don't insist.

**Comment by Aadityajoshi151** [comment]
Yes, I think it can be more user-friendly because, for a developer, it would make sense but if someone is not from a programming background, he/she may not understand the "JSON" terminology.
I will make the required changes.

**Comment by Aadityajoshi151** [comment]
Hello, I have made the required changes in the names of menu items and also in the readme file to the best of my knowledge.
The "Prettier" extension on my vs-code has refactored the readme file without changing the order or content of the file. I hope that is not an issue.
Thank You
